YourDay.MvcSite/Controllers/Common/FooterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace YourDay.MvcSite.Controllers.Common
{
    public class TemplateController : Controller
    {
        //
        // GET: /Footer/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Footer()
        {
            double i = 0;
            var mapItemsList = BLL.Get.Categories()
               .OrderBy(x => x.Title)
               .GroupBy(x => Math.Floor(++i / 11));

            ViewBag.CategoryLinks = mapItemsList;

            if (YourDay.Security.MembershipUser.CurrentUser != null)
            {
                ViewBag.HeaderLinks = Constants.Strings.ContractorHeaderLinkDictionary;
            }

            ViewBag.AdvLinks = Constants.Strings.BottomProjectLinks;
            return PartialView();
        }

    }
}

YourDay.MvcSite/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace YourDay.MvcSite.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View();
        }
    }
}

YourDay.MvcSite/Controllers/MeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace YourDay.MvcSite.Controllers
{
    public class MeController : Controller
    {
        //
        // GET: /Me/

        public ActionResult Index()
        {
            return RedirectToActionPermanent("Events");
        }

        public ActionResult Events()
        {
            return View();
        }

        public ActionResult Messages()
        {
            return View();
        }

        public ActionResult Favourites()
        {
            return View();
        }

        public ActionResult Preferences()
        {
            return View();
        }

    }
}

YourDay.MvcSite/Controllers/SubcategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace YourDay.MvcSite.Controllers
{
    public class SubcategoryController : Controller
    {
        //
        // GET: /Subcategory/

        
       
        int takenCount = 0;
        int countOnRequest = 10;

        public ActionResult Index(int id)
        {
            if(BLL.Get.SubCategory(id) == null)
                return null;

            var contractorGroups = BLL.Get.ContractorsGroupByPlateSize(id);


           


            return View();
        }

        [HttpGet]
        public JsonResult MoreContractors()
        {
            return View();
        }

    }
}

YourDay.MvcSite/Views/Home/Articles.cshtml
@using YourDay.BLL
<section class="b-promo-news col left">
    <header class="header-more">
        <h2 class="featured">Статьи </h2>
        <a href="javascript:;" class="more">Все статьи</a>
    </header>
    @foreach (var item in Get.Articles().Take(2))
    {
        <div class="news-item">
            <img src="@Manager.GetArticleThumbImg(item.Id, true)" alt="photo" class="media">
            <h4 class="a-3"><a href="@Manager.GetArticleLink(item.Id)">@item.Title</a></h4>
            @Manager.GetShortContent(item.Content, 50)
        </div>
    }
</section>

YourDay.MvcSite/Views/Home/BestContractors.cshtml
@using YourDay.BLL


<!-- Best photographers -->
<section class="b-best-photographers">
    <header>
        <h2 class="featured">Лучшие фотографы</h2>
    </header>
    <div class="b-twocol devider clearfix">
        <div class="col left">
            <ol>
                @foreach (var contractor in Manager.GetTopSixOnMain(Admin.DefaultSubcategoryForTopSix()).Take(3))
                {
                    <li>
                        <figure class="b-userpick clearfix">
                            <img src="@contractor.GetAvatarImage(52)" alt="@contractor.FullName">
                            <figcaption>
                                <h4 class="username"><a href="#">@contractor.FullName</a></h4>
                                @*Специализация: <a href="javascript:;">шоу-мен</a>*@</figcaption>
                        </figure>
                    </li>
                }
            </ol>
        </div>
        <div class="col right">
            <ol start="4">
                 @foreach (var contractor in Manager.GetTopSixOnMain(Admin.DefaultSubcategoryForTopSix()).Skip(3))
                {
                    <li>
                        <figure class="b-userpick clearfix">
                            <img src="@contractor.GetAvatarImage(52)" alt="@contractor.FullName">
                            <figcaption>
                                <h4 class="username"><a href="#">@contractor.FullName</a></h4>
                                @*Специализация: <a href="javascript:;">шоу-мен</a>*@</figcaption>
                        </figure>
                    </li>
                }
            </ol>
        </div>
    </div>
</section>
<!-- /Best photographers -->

YourDay.MvcSite/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Event Wizard -->
<nav class="l-wrap b-event-wizard clearfix">
	<ol>
		<li class="step">
			<h3>1 Шаг. Создайте событие</h3>
			Просто создайте и опубликуйте свое событие.<br>
			Контрагенты сами предложат Вам свои услуги.
		</li>
		<li class="step">
			<h3>2 Шаг. Выберите контрагентов</h3>
			Подберите контрагентов, просматривая  фото<br>
			и видео-отчеты о событиях.
		</li>
		<li class="go">
			<a href="javascript:;" class="ui-button flexwidth" id="listMore"><span>Устроить праздник!</span></a>
		</li>
	</ol>
</nav>
<!-- /Event Wizard -->
<!-- Content -->
<div class="l-wrap clearfix">
	<div class="l-content-wrap">
		<div class="l-content">

			<!-- Promo media -->
			<div class="b-promo-media" id="promoMedia">
				<img src="http://dummyimage.com/720x270/09f/fff.gif&text=one" alt="Banner 1">
				<img src="http://dummyimage.com/720x270/09f/fff.gif&text=two" alt="Banner 2">
				<img src="http://dummyimage.com/720x270/09f/fff.gif&text=three" alt="Banner 3">
			</div>
			<script>
				$(function(){
					/* Used http://www.zurb.com/playground/orbit-jquery-image-slider */
					$('#promoMedia').orbit({
						bullets: true,
						//bulletThumbs: true,
						});
					});
			</script>
			<!-- /Promo media -->

			<!-- Best photographers -->
			@Html.Partial("BestContractors")
			<!-- /Best photographers -->
		
		</div>
	</div>
	@Html.Partial("LeftMenu")
</div>
<!-- /Content -->


<div class="l-wrap clearfix">
	<section class="b-event-reports promo-panel">
		<header>
			<h2 class="featured">Отчет о событиях</h2>
		</header>
		<div class="b-twocol asymmetric clearfix">
			<div class="col left">
				<div class="b-media-gallery">
					<figure class="big-preview">
						<img src="http://dummyimage.com/480x265/09f/fff.gif" alt="Big photo" class="media">
						<figcaption class="descr">
							Мы такие тусим на фотке, я такой типа «Эй патипипл камон!!! А телка такая: «Да, да! Давай ещё!!! Дава-давай-давай-давай!», а мой кореш такой, типа тоже весь дико угарает, а еще я забыл надеть трусы и мне за это пиздюль под глаз повесили. Короче, офигительно оттусили, вот бы повторить!
						</figcaption>
					</figure>

					<nav class="media-list clearfix">
						<ul>
							<li>
								<a href="javascript:;">
									<img src="http://dummyimage.com/50x50/09f/fff.gif" alt="Small photo" class="media">
								</a>
							</li>
							<li>
								<a href="javascript:;">
									<img src="http://dummyimage.com/50x50/09f/fff.gif" alt="Small photo" class="media">
								</a>
							</li>
							<li>
								<a href="javascript:;">
									<img src="http://dummyimage.com/50x50/09f/fff.gif" alt="Small photo" class="media">
								</a>
							</li>
							<li>
								<a href="javascript:;">
									<img src="http://dummyimage.com/50x50/09f/fff.gif" alt="Small photo" class="media">
								</a>
							</li>
							<li>
								<a href="javascript:;">
									<img src="http://dummyimage.com/50x50/09f/fff.gif" alt="Small photo" class="media">
								</a>
							</li>
							<li>
								<a href="javascript:;">
									<img src="http://dummyimage.com/50x50/09f/fff.gif" alt="Small photo" class="media">
								</a>
							</li>
							<li>
								<a href="javascript:;">
									<img src="http://dummyimage.com/50x50/09f/fff.gif" alt="Small photo" class="media">
								</a>
							</li>
							<li>
								<a href="javascript:;">
									<img src="http://dummyimage.com/50x50/09f/fff.gif" alt="Small photo" class="media">
								</a>
							</li>
						</ul>
					</nav>
				</div>
			</div>
			<div class="col right">
				<img src="http://dummyimage.com/440x329/09f/fff.gif" alt="Video" class="media">
			</div>
		</div>
	</section>

	<div class="b-twocol asymmetric promo-panel clearfix">
		@{Html.RenderPartial("Articles");}		
		@{Html.RenderPartial("News");}
	</div>
</div>
<!-- /Promo content -->

YourDay.MvcSite/Views/Home/LeftMenu.cshtml
<aside class="l-sidebar">
    <nav class="nav-main">
        <ul>
            @foreach (var item in YourDay.BLL.Get.Categories().OrderBy(x => x.Title))
            {
                <li class="nav-item"><a href="@YourDay.BLL.Manager.GetCategoryLink(item.Id)">
                    @item.Title
                </a></li>
            }
        </ul>
    </nav>
</aside>

YourDay.MvcSite/Views/Home/News.cshtml
@using YourDay.BLL
<section class="b-promo-news col right">
    <header class="header-more">
        <h2 class="featured">Новости </h2>
        <a href="javascript:;" class="more">Все ноовости</a>
    </header>
@foreach(var item in  Get.News().Take(4))
{
    <div class="news-item">
        <span class="date">@item.DateTime.ToShortDateString()</span>
        <h4 class="a-3"><a href="@Manager.GetNewsLink(item.Id)">@item.Title</a></h4>
            @Manager.GetShortContent(item.Content, 25)
    </div>
    }
</section>

YourDay.MvcSite/Views/Me/Events.cshtml
@{
    ViewBag.Title = "Events";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Events</h2>

YourDay.MvcSite/Views/Me/Favourites.cshtml
@{
    ViewBag.Title = "Favourites";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Favourites</h2>

YourDay.MvcSite/Views/Me/Messages.cshtml
@{
    ViewBag.Title = "Messages";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Messages</h2>

YourDay.MvcSite/Views/Me/Preferences.cshtml
@{
    ViewBag.Title = "Preferences";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Preferences</h2>

YourDay.MvcSite/Views/Shared/BottomMenu.cshtml
<ul>
@foreach (dynamic link in ViewBag.Links)
{ 
    <li>@link.Title</li>
}
</ul>

YourDay.MvcSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <meta charset="utf-8">
	<link rel="shortcut icon" href="favicon.ico">
	<link rel="stylesheet" type="text/css"  href="@Url.Content("~/Content/css/normalize.css")" />
	<link rel="stylesheet" type="text/css"  href="@Url.Content("~/Content/css/style.css")" />
	<link rel="stylesheet" type="text/css"  href="@Url.Content("~/Content/css/typo.css")" />
	<link rel="stylesheet" type="text/css"  href="@Url.Content("~/Content/css/nav.css")" />
	<link rel="stylesheet" type="text/css"  href="@Url.Content("~/Content/css/panel.css")" />
	<link rel="stylesheet" type="text/css"  href="@Url.Content("~/Content/css/icons.css")" />
	<link rel="stylesheet" type="text/css"  href="@Url.Content("~/Content/css/form.css")" />
	<link rel="stylesheet" type="text/css"  href="@Url.Content("~/Content/css/table.css")" />
	<link rel="stylesheet" type="text/css"  href="@Url.Content("~/Content/css/base64.css")" />
	<link rel="stylesheet" type="text/css"  href="@Url.Content("~/Content/css/orbit-1.2.3.css")" />
	
	<!--[if lte IE 8 ]><script src="js/html5.js"></script><![endif]-->
	<script src="@Url.Content("~/Scripts/jquery.min.js")" type="text/javascript"></script>
	<script src="@Url.Content("~/Scripts/jquery.tmpl.min.js")" type="text/javascript"></script>
	<script src="@Url.Content("~/Scripts/customize.js")" type="text/javascript"></script>
	<script src="@Url.Content("~/Scripts/baseyourday.js")" type="text/javascript"></script>
	<script src="@Url.Content("~/Scripts/jquery.orbit-1.2.3.js")" type="text/javascript"></script>


</head>

<body>
 


<header>

	<!-- Unlogged user menu -->
	<div class="l-wrap b-user-menu clearfix">
		<nav>
			<ul class="nav-usermenu clearfix">
				<li>@*Ваш город: <strong>Санкт-Петербург</strong><a href="#" class="i-dd-wrap"><i class="i i-dd"></i></a>*@</li>
				<li class="login-action login"><a href="#">Вход</a></li>
				<li class="login-action register"><a href="#">Регистрация</a></li>
			</ul>
		</nav>
	</div>
	<!-- /Unlogged user menu -->

	<!-- Logo -->
	<div class="b-lamb">
		<div class="l-wrap">
			<img src="@Url.Content("~/Content/i/logo.png")" alt="Your Day" class="logo">
			<div class="banner">
				<img src="@Url.Content("~/Content/i/banner.png")" alt="Banner">
			</div>
		</div>
	</div>
	<!-- /Logo -->

</header>

   @RenderBody()

<footer>
@{Html.RenderAction("Footer", "Template");}
	

	<!-- Copy  -->
	<div class="l-wrap b-copyrights">
		<span class="copy">&copy; 2011 &laquo;YourDay.ru&raquo;</span>
		<nav class="nav-inline nav-about">
			<ul>
				<li><a href="#">О проекте</a></li>
				<li><a href="#">Реклама на сайте</a></li>
				<li><a href="#">Контакты</a></li>
			</ul>
		</nav>
		<span class="art">Дизайн создан в <a href="http://www.arthorse.ru/">Arthorse</a></span>
	</div>
	<!-- /Copy  -->

</footer>


</body>
</html>

YourDay.MvcSite/Views/Subcategory/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<!-- Content -->
<div class="l-wrap clearfix">
	<div class="l-content-wrap">
		<div class="l-content">
			<div class="b-list-items contractors" id="listItems">

				<!-- Contractor item -->
					<div class="b-list-item clearfix">
						<table class="va-top">
							<col width="70">
							<col width="40%">
							<col width="25%">
							<col>
							<tbody>
								<tr>
									<td rowspan="2"><img src="http://dummyimage.com/52x52/09f/fff.gif" alt="Семен Пешка"></td>
									<td>
										<h3><a href="#">Семен Пешка</a></h3>
									</td>
								</tr>
								<tr>
									<td>
										Специализация: <a href="javascript:;">фотограф</a>, <a href="javascript:;">стриптизер</a><br>
										Статус: <span class="c-3">сейчас на сайте</span>
									</td>
									<td>
										Отзывы: <a href="javascript:;" class="c-3">125</a> / <a href="javascript:;" class="c-4">12</a><br>
										Опыт: <a href="javascript:;">24 события</a>
									</td>
									<td>
										Город: <a href="javascript:;">Санкт-Петербург</a><br>
										Время: <span class="c-3">с 12:00 до 21:00</span>
									</td>
								</tr>
							</tbody>
						</table>
						
						<nav class="media-list clearfix">
							<ul>
								<li><a href="javascript:;"><img src="http://dummyimage.com/210x210/09f/fff.gif" alt="Photo" /></a></li>
								<li><a href="javascript:;"><img src="http://dummyimage.com/210x210/09f/fff.gif" alt="Photo" /></a></li>
								<li><a href="javascript:;"><img src="http://dummyimage.com/210x210/09f/fff.gif" alt="Photo" /></a></li>
							</ul>
						</nav>
						
						<a href="#"><i class="i i-to-fav i-left"></i> Добавить в избранное</a>
						<span class="media-summary">
							<a href="javascript:;">135 фотографий</a> / <a href="javascript:;">4 видео</a>
						</span>
						
					</div>
				<!-- /Contractor item -->				
				<!-- Contractor short item -->
					<div class="b-list-item clearfix">
						<table class="va-top">
							<col width="70">
							<col width="40%">
							<col width="25%">
							<col>
							<tbody>
								<tr>
									<td rowspan="2"><img src="http://dummyimage.com/52x52/09f/fff.gif" alt="Семен Пешка"></td>
									<td>
										<h3><a href="#">Семен Пешка</a></h3>
									</td>
								</tr>
								<tr>
									<td>
										Специализация: <a href="javascript:;">фотограф</a>, <a href="javascript:;">стриптизер</a><br>
										Статус: <span class="c-3">сейчас на сайте</span>
									</td>
									<td>
										Отзывы: <a href="javascript:;" class="c-3">125</a> / <a href="javascript:;" class="c-4">12</a><br>
										Опыт: <a href="javascript:;">24 события</a>
									</td>
									<td>
										Город: <a href="javascript:;">Санкт-Петербург</a><br>
										Время: <span class="c-3">с 12:00 до 21:00</span>
									</td>
								</tr>
							</tbody>
						</table>
					</div>
				<!-- /Contractor short item -->	

			</div>
			<div class="b-list-more">
				<a href="javascript:;" class="ui-button" id="listMore"><span>Показать еще</span></a>
			</div>
		</div>
	</div>
	<aside class="l-sidebar">
		<nav class="nav-main">
			<ul>
				<li class="nav-item"><a href="#">Рестораны и банкетные залы</a></li>
				<li class="nav-item"><a href="#">Транспорт</a></li>
				<li class="nav-item"><a href="#">Фото, видео, печать</a></li>
				<li class="nav-item"><a href="#">Ведущие</a></li>
				<li class="nav-item expanded"><a href="#">Музыканты</a></li>
					<li class="subnav-item"><a href="#">Вокалисты</a></li>
					<li class="subnav-item"><a href="#">Музыкальные коллективы</a></li>
					<li class="subnav-item"><a href="#">Музыкальное оформление</a></li>
					<li class="subnav-item"><a href="#">Танцевальные номера</a></li>
					<li class="subnav-item"><a href="#">Шоу балеты</a></li>
					<li class="subnav-item cur"><a href="#">Варьете </a></li>
					<li class="subnav-item"><a href="#">Эротическое шоу</a></li>
					<li class="subnav-item"><a href="#">Цирковые артисты</a></li>
					<li class="subnav-item"><a href="#">Иллюзионисты и фокусники</a></li>
					<li class="subnav-item"><a href="#">Клоуны</a></li>
					<li class="subnav-item"><a href="#">Ростовые куклы</a></li>
					<li class="subnav-item"><a href="#">Комические шоу и номера</a></li>
					<li class="subnav-item"><a href="#">Пародисты</a></li>
					<li class="subnav-item"><a href="#">Оригинальные шоу и номера</a></li>
					<li class="subnav-item"><a href="#">Звезды эстрады</a></li>
					<li class="subnav-item"><a href="#">Dj-еи</a></li>
				<li class="nav-item"><a href="#">Декораторы, флористика</a></li>
				<li class="nav-item"><a href="#">Платья, костюмы, обувь</a></li>
				<li class="nav-item"><a href="#">Красота и здоровье</a></li>
				<li class="nav-item"><a href="#">Ювелирные украшения</a></li>
				<li class="nav-item"><a href="#">Свет, звук, спецэффекты</a></li>
				<li class="nav-item"><a href="#">Организация мероприятий</a></li>
				<li class="nav-item"><a href="#">Гостиницы и базы отдыха</a></li>
				<li class="nav-item"><a href="#">Путешествия</a></li>
				<li class="nav-item"><a href="#">Торты</a></li>
				<li class="nav-item"><a href="#">ЗАГСы</a></li>
				<li class="nav-item"><a href="#">Другое</a></li>
			</ul>
		</nav>
	</aside>
</div>
<!-- /Content -->

YourDay.MvcSite/Views/Template/Footer.cshtml
<!-- Additional info  -->
<div class="b-additional">
    <div class="l-wrap clearfix">
        <div class="b-col left">
            <h3>Каталог контрагентов</h3>
            <nav class="nav-additional contractors">
                @foreach (var item in (ViewBag.CategoryLinks as IEnumerable<IGrouping<double, YourDay.POCO.Category>>))
                {
                    <ul>
                        @foreach (var category in item)
                        {
                            <li><a href="@YourDay.BLL.Manager.GetCategoryLink(category.Id)">
                                @category.Title
                            </a></li> 
                        }
                    </ul> 
                }
            </nav>
        </div>
        <div class="b-col center">
            @if (ViewBag.HeaderLinks != null)
            {
                <h3>Личный кабинет</h3>
                <nav class="nav-additional">
                    <ul>
                        @foreach (var item in (ViewBag.HeaderLinks as Dictionary<string, string>))
                        { 
                            <li><a href="@item.Value">@item.Key</a></li>
                        }
                    </ul>
                </nav>
            }
            <h3>О проекте</h3>
            <nav class="nav-additional">
                <ul>
                    @foreach (var item in (ViewBag.AdvLinks as Dictionary<string, string>))
                    {
                        <li><a href="@item.Value">@item.Key</a></li>
                    }
                </ul>
            </nav>
        </div>
        <div class="b-col right">
            <div class="b-intro">
                <div class="intro-text">
                    YourDay.ru поможет исполнить ваши желания, организовать свадьбу и&nbsp;день рождения.
                    Здесь Вы&nbsp;найдете лучшие сценарии, удобный календарь праздников. Проведение
                    и&nbsp;организация праздников (вечеринок, торжеств и&nbsp;других праздничных мероприятий)
                    в&nbsp;Москве и&nbsp;Санкт-Петербурге.
                </div>
            </div>
            <div class="b-follow-us">
                Следите за нами: <a href="#"><i class="i i-facebook"></i></a><a href="#"><i class="i i-twitter">
                </i></a><a href="#"><i class="i i-google-plus"></i></a><a href="#"><i class="i i-vkontakte">
                </i></a>
            </div>
        </div>
    </div>
</div>
<!-- /Additional info  -->